FROM maven:3.9-eclipse-temurin-21 AS development

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

ENV SPRING_DEVTOOLS_RESTART_ENABLED=true
ENV SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/src
ENV SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=1000
ENV SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=400

EXPOSE 8081

CMD ["mvn", "spring-boot:run"]
