#Что нужно сделать:
#  - Настроить параметры безопасности и JWT.

server:
  port: ${APP_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      pool-name: poll-pool
      maximum-pool-size: 10
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yml

  security:

jwt:
  secret: ${JWT_KEY}
  expiration: ${JWT_EXPIRATION}

springdoc:
  api-docs:
    path: '/api-doc'
  swagger-ui:
    path: '/swagger-ui'
