#Что нужно сделать:
#  - Настроить параметры безопасности и JWT.

server:
  port: ${APP_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      pool-name: poll-pool
      maximum-pool-size: 10
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: false
#    change-log: classpath:db/migration/changelog-master.yml
#    referenceUrl: hibernate:spring:com.example.bankcards.entity?dialect=org.hibernate.dialect.PostgreSQLDialect
#    url: ${spring.datasource.url}
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}


springdoc:
  api-docs:
    path: '/api-doc'
  swagger-ui:
    path: '/swagger-ui'

